# RSS Article Analyzer Configuration
# This file provides default configuration that can be overridden by environment variables

# API Configuration
api:
  provider: "anthropic"  # Options: anthropic, mistral, openai
  anthropic:
    model: "claude-3-5-sonnet-20241022"
    max_retries: 3
    base_delay: 1.0
    timeout: 60
  mistral:
    model: "mistral-large-latest"
    max_retries: 3
    base_delay: 1.0
    timeout: 60
  openai:
    model: "gpt-4"
    max_retries: 3
    base_delay: 1.0
    timeout: 60

# RSS Configuration
rss:
  feed_url: "https://bg.raindrop.io/rss/public/57118738"
  user_agent: "RSS-Article-Analyzer/1.0"
  timeout: 30

# Database Configuration
database:
  path: "data/articles.db"
  backup_enabled: true
  cleanup_logs_days: 30

# Scraping Configuration
scraper:
  delay_between_requests: 1.0
  max_retries: 3
  timeout: 30
  respect_robots_txt: true
  follow_links: true
  max_linked_articles: 3

# Processing Configuration
processing:
  max_articles_per_run: 30
  batch_size: 5
  concurrent_requests: 1

# Output Configuration
output:
  directory: "output"
  reports:
    main_filename: "article_analysis_report.md"
    summary_filename: "summary_report.md"
    json_filename: "articles_export.json"
    csv_filename: "articles_export.csv"

  formats:
    include_toc: true
    include_stats: true
    truncate_csv_fields: 500

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# Content Processing
content:
  max_content_length: 50000
  min_content_length: 100

# Filtering
filters:
  min_confidence_score: 1
  exclude_domains: []
  include_domains: []

# Performance
performance:
  enable_caching: true
  cache_ttl_seconds: 3600
  memory_limit_mb: 512
