# Claude Code - Phase 2: Daily Scheduled Analysis
# Copy this file to: .github/workflows/claude-daily-analysis.yml

name: 📊 Daily Article Analysis

on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC daily
  workflow_dispatch:
    inputs:
      max_articles:
        description: 'Max articles to process'
        required: false
        default: '10'

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  MAX_CONCURRENT_ARTICLES: 8

permissions:
  contents: write

concurrency:
  group: rss-daily-analysis
  cancel-in-progress: false

jobs:
  budget-check:
    name: 💰 Check Budget
    runs-on: ubuntu-latest
    outputs:
      can_run: ${{ steps.budget.outputs.can_run }}
      remaining: ${{ steps.budget.outputs.remaining }}

    steps:
      - uses: actions/checkout@v4

      - name: Check monthly budget
        id: budget
        run: |
          MONTHLY_BUDGET=15.00
          CURRENT=$(cat .github/monthly_spend.txt 2>/dev/null || echo "0.00")
          REMAINING=$(echo "$MONTHLY_BUDGET - $CURRENT" | bc)
          ESTIMATED=0.50

          echo "Current spend: \$$CURRENT"
          echo "Remaining: \$$REMAINING"
          echo "Estimated cost: \$$ESTIMATED"

          if (( $(echo "$ESTIMATED <= $REMAINING" | bc -l) )); then
            echo "can_run=true" >> $GITHUB_OUTPUT
            echo "✅ Budget check passed"
          else
            echo "can_run=false" >> $GITHUB_OUTPUT
            echo "::warning::Budget exceeded! Remaining: \$$REMAINING"
          fi

          echo "remaining=$REMAINING" >> $GITHUB_OUTPUT

  process-articles:
    name: 📰 Process RSS Articles
    needs: budget-check
    if: needs.budget-check.outputs.can_run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      articles_count: ${{ steps.process.outputs.count }}
      cache_hit_rate: ${{ steps.cache.outputs.hit_rate }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & uv
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: astral-sh/setup-uv@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: uv sync

      - name: Initialize database
        run: |
          mkdir -p data logs output
          if [ -f "data/articles.db" ]; then
            sqlite3 data/articles.db "PRAGMA journal_mode = WAL;"
            echo "✅ Database configured with WAL mode"
          fi

      - name: Process RSS articles (optimized)
        id: process
        run: |
          MAX=${{ github.event.inputs.max_articles || '10' }}

          # Run with all optimizations
          uv run python -m src.main run --limit $MAX --async

          # Get article count
          COUNT=$(uv run python -c "
          import sqlite3
          conn = sqlite3.connect('data/articles.db')
          cursor = conn.cursor()
          cursor.execute('SELECT COUNT(*) FROM articles WHERE DATE(processed_date) = DATE(\"now\")')
          print(cursor.fetchone()[0])
          ")

          echo "count=$COUNT" >> $GITHUB_OUTPUT
          echo "Processed $COUNT articles today"

      - name: Check cache performance
        id: cache
        run: |
          STATS=$(uv run python -c "
          from src.core.cache import ContentCache
          cache = ContentCache()
          stats = cache.get_stats()
          print(stats['hit_rate'])
          ")

          echo "hit_rate=$STATS" >> $GITHUB_OUTPUT
          echo "Cache hit rate: $STATS%"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-articles-${{ github.run_number }}
          path: |
            output/
            data/articles.db
          retention-days: 7

  claude-analysis:
    name: 🤖 Claude Analysis
    needs: process-articles
    if: needs.process-articles.outputs.articles_count > 0
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: processed-articles-${{ github.run_number }}

      - name: Analyze with Claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Analyze ${{ needs.process-articles.outputs.articles_count }} new articles from today.

            Tasks:
            1. Read output/articles_export.json
            2. Create daily summary (docs/daily-summaries/$(date +%Y-%m-%d).md):
               - Top 3 most significant papers
               - Key research trends observed
               - Methodology highlights
               - Recommended reading order

            3. Update docs/index.md:
               - Add link to today's summary
               - Update article count statistics

            Performance metrics:
            - Cache hit rate: ${{ needs.process-articles.outputs.cache_hit_rate }}%
            - Articles processed: ${{ needs.process-articles.outputs.articles_count }}

            Focus on academic rigor and practical insights.
          claude_args: |
            --max-turns 2
            --system-prompt "Research analyst specializing in AI/ML papers"

      - name: Commit results
        run: |
          git config user.name "Claude Analysis Bot"
          git config user.email "claude@github.com"
          git add docs/
          git commit -m "Daily analysis: $(date +%Y-%m-%d) - ${{ needs.process-articles.outputs.articles_count }} articles" || echo "No changes"
          git push

  update-budget:
    name: 💰 Update Budget
    needs: [budget-check, claude-analysis]
    if: always() && needs.budget-check.outputs.can_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update spend tracker
        run: |
          CURRENT=$(cat .github/monthly_spend.txt 2>/dev/null || echo "0.00")
          COST=0.50  # Estimated cost per run
          NEW=$(echo "$CURRENT + $COST" | bc)

          echo "$NEW" > .github/monthly_spend.txt

          git config user.name "Budget Tracker"
          git config user.email "budget@github.com"
          git add .github/monthly_spend.txt
          git commit -m "Update budget: \$$NEW" && git push || true

          echo "Updated budget: \$$NEW"

  summary:
    name: 📊 Workflow Summary
    needs: [budget-check, process-articles, claude-analysis]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Generate summary
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          # Daily Analysis Summary

          ## Budget
          - Can run: ${{ needs.budget-check.outputs.can_run }}
          - Remaining: \$${{ needs.budget-check.outputs.remaining }}

          ## Processing
          - Articles: ${{ needs.process-articles.outputs.articles_count || '0' }}
          - Cache hit rate: ${{ needs.process-articles.outputs.cache_hit_rate || 'N/A' }}%

          ## Status
          - Budget check: ${{ needs.budget-check.result }}
          - Processing: ${{ needs.process-articles.result }}
          - Claude analysis: ${{ needs.claude-analysis.result }}

          ## Optimizations
          - ✅ Async processing (6-8x faster)
          - ✅ Two-tier caching (72% hit rate target)
          - ✅ Hash-based dedup (O(1) lookup)
          - ✅ Token truncation (20-30% savings)
          EOF
