"""Exception classes"""

from .exceptions import (
    APIClientError,
    APIConnectionError,
    APIQuotaExceededError,
    APIRateLimitError,
    APIResponseError,
    ConfigurationError,
    ContentProcessingError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseMigrationError,
    InvalidURLError,
    ReportGenerationError,
    RSSAnalyzerError,
    RSSParsingError,
    ScrapingError,
    ScrapingTimeoutError,
    ValidationError,
)

__all__ = [
    "APIClientError",
    "APIConnectionError",
    "APIQuotaExceededError",
    "APIRateLimitError",
    "APIResponseError",
    "ConfigurationError",
    "ContentProcessingError",
    "DatabaseConnectionError",
    "DatabaseError",
    "DatabaseMigrationError",
    "InvalidURLError",
    "RSSAnalyzerError",
    "RSSParsingError",
    "ReportGenerationError",
    "ScrapingError",
    "ScrapingTimeoutError",
    "ValidationError",
]
